### ISSUE TITLE
Can't [Log in]　In WireCloud (probably Keyrock issue)

### ISSUE THREAD

**Issue by hsakamoto123** [FIWARE/tutorials.Application-Mashup#12]
https://github.com/FIWARE/tutorials.Administrating-XACML/issues/6

I think the same.
It seems that the three columns `regex_entity_ids`, `regex_attributes`, and `regex_types` have not been added to the permission table.

Container log:
{"log":"ERROR 1136 (21S01) at line 809: Column count doesn't match value count at row 1\n","stream":"stderr","time":"2022-12-20T14:31 :08.578031134Z"}

**Comment by fisuda** [comment]
There is a difference in error messages. Is it really the same cause?

Your report in https://github.com/FIWARE/tutorials.Administrating-XACML/issues/6:
```
{"log":"2022-12-19T10:19:13.333Z idm:api-permissions Error: SequelizeDatabaseError: Unknown column 'regex_entity_ids' in 'field list'\n","stream":"stderr","time":"2022-12-19T10:19:13.333596701Z"}
```

**Comment by hsakamoto123** [comment]
I have verified that the permission table does not have the three columns.
The mysql message also seemed to be column related, so I interpreted it as a similar problem.
The message is certainly different, so there is also the possibility of another problem.
I apologize for making a judgmental statement despite the fact that the grounds are weak.
However, since I do not know the correct setting of the tutorial, it is honestly difficult to investigate.

I changed mysql-data/backup.sql and tried adding three columns, but the following error occurred.

{"log":"ERROR 1136 (21S01) at line 824: Column count doesn't match value count at row 1\n","stream":"stderr","time":"2022-12-20T16:44 :13.189169061Z"}

The screen shows the following error:
Invalid client: `redirect_uri` does not match client value

I will check it a bit more.

Changing the oauth_client settings made it work.
Sincerest apologies.
I will withdraw this issue.

**Comment by hsakamoto123** [comment]
I decided that it was a problem with the settings of my own environment, so I will withdraw it.

**Comment by jason-fox** [comment]
This tutorial is currently stuck using **Keyrock 8.1.0**, since upgrading to  **8.3.0**  won't work due to the presence of the  `/user` endpoint bug.  That bug was fixed by https://github.com/ging/fiware-idm/pull/306 but there has not yet been a full Keyrock release with the fix made available.

@apozohue10 -  could you make a new 8.3.1 patch release of **Keyrock** so the tutorial can be updated?

**Comment by apozohue10** [comment]
Hi Jason,

I will try to make the release today.

BR
